### ISSUE TITLE
indir.com logo

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#13]
indir.com logosu eklensin. Sosyal medya sponsorları başlığı altında

**Comment by onuryurtturk** [comment]
Gönderildi! https://drive.google.com/file/d/0B4nqLP3OoCKKWF93TS1SeFFVVnc/edit?usp=sharing

**Comment by cerenagdas** [comment]
Site bültenimizi yayınladı, bir an önce logolarına yer vermemiz gerek.
