### ISSUE TITLE
PAU IEEE logosu

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#16]
Onur'dan alınacak PAU IEEE logosu destekleyenler kısmına eklensin

**Comment by onuryurtturk** [comment]
logo iletildi :)

**Comment by onuryurtturk** [comment]
https://drive.google.com/file/d/0B4nqLP3OoCKKYnFrVE1DMjVPYWM/edit?usp=sharing

**Comment by kemalkanok** [comment]
@onuryurtturk logolari proje ekleyip commitde yapabilrsin:)
