### ISSUE TITLE
Twitter ve facebook linkleri 

### ISSUE THREAD

**Issue by necatikartal** [womandevelopersday/womandevelopersday.org#19]
pau fsc yerine womandevelopersday ile ilgili olarak degistirilmeli (twitter ve facebook)

**Comment by kemalkanok** [comment]
içerik gönderin :+1:

**Comment by cerenagdas** [comment]
Facebook : https://www.facebook.com/womandevelopersday
Twitter      : https://twitter.com/WomanDevelopers
