### ISSUE TITLE
Yeni wdd logosu

### ISSUE THREAD

**Issue by onuryurtturk** [womandevelopersday/womandevelopersday.org#2]
Yeni logoyu email attım

**Comment by kemalkanok** [comment]
yeni bir issueya yönlendirildi -> #4

**Comment by onuryurtturk** [comment]
yenii logo düzenlendi

2014-04-15 21:25 GMT+03:00 Kemal Kanok notifications@github.com:

> Closed #2https://github.com/womandevelopersday/womandevelopersday.org/issues/2
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/womandevelopersday/womandevelopersday.org/issues/2
> .

## 

_ONUR YURTTÜRK_
