### ISSUE TITLE
Sosyal Medya Kulübü Logo

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#20]
Sosyal Medya Kulübü logosu eklensin. medya sponsorları başlığı altında. Onur Logoyu iletecek

**Comment by onuryurtturk** [comment]
Logo upload edildi : https://drive.google.com/file/d/0B4nqLP3OoCKKQ09qaGwxV1Z4eXM/edit?usp=sharing
