### ISSUE TITLE
Sponsorluk başlıkları

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#29]
"Platin Sponsorlar"  başlığı gibi olsun diğer sponsorluk başlıklarımız.

**Comment by kemalkanok** [comment]
Kesin karar mı böyle bence onurla konuşup anlaşın :)

**Comment by cerenagdas** [comment]
Platin dışındaki başlıklar dikkat çekmediği için okunmuyor, araya kaynıyor bu yazı tipiyle

**Comment by kemalkanok** [comment]
bence hala onurdan onay almalıyız çünkü çok fazla değişiyor  bu aralar tasarım
