### ISSUE TITLE
Konuşmacı Burcu Sözay

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#31]
Burcu Sözay'a ait tanımlama sitemize eklensin. Drive üzerinde mevcut

Oturum saatleri : 15.30-16.15

Foto Onur tarafından iletilecek.

**Comment by kemalkanok** [comment]
bu ekleme işlemi resim geldiğinde yapılacak

**Comment by cerenagdas** [comment]
Eklemeleri daha dikkatli yapalım oturum saatini yukarıda belirtmiştim ancak yanlış girilmiş

**Comment by kemalkanok** [comment]
çok içerik giriyoruz normaldir bence :) ama yinede pardon :/

**Comment by cerenagdas** [comment]
Sen de haklısın tabii :)
