### ISSUE TITLE
Fotoğraflar

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#32]
Konuşmacı fotoğrafları hizalı değil

**Comment by kemalkanok** [comment]
Biraz daha aciklayin lutfen

**Comment by kemalkanok** [comment]
Biraz daha aciklayin lutfen

**Comment by cerenagdas** [comment]
ilk konuşmacıların fotoğrafları hemen isimlerinin yanındayken aşağıya doğru indikçe diğer konuşmacıların fotoğrafları isimlerinden daha aşağı kaymış
