### ISSUE TITLE
Php mentorü Cemile Sarıcaoğlu

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#36]
Cemile Sarıcaoğlu bilgileri siteye eklensin. Foto onur tarafından gönderilecek

**Comment by cerenagdas** [comment]
Atölye saatleri 14:30 - 18:00

**Comment by kemalkanok** [comment]
drive'da mevcut mudur?

**Comment by cerenagdas** [comment]
mevcut

**Comment by cerenagdas** [comment]
fotoğrafını maille gönderdim

**Comment by cerenagdas** [comment]
Php "Atölyesi" diye ekleyebilirsek sevinirim. İçeriğe yazmayı unutmuşum. Kusura bakma Kemal :)
