### ISSUE TITLE
Pamukkale Ünviersitesit Teknokent logosu

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#37]
Pamukkale Ünviersitesit Teknokent logosu DESTEKLEYENLER arasına eklensin. Logo Onur tarafından iletilecek

**Comment by kemalkanok** [comment]
ben logoları ayarlıyıp atıcam bitince bir mail çakarım ceren sende kontrol edersin en azından yeni logolar gelene kadar idare eder.

**Comment by cerenagdas** [comment]
cebit logosu konusunda dikkatli olalım. sana logoyu iletiyorum maille

**Comment by kemalkanok** [comment]
ok

**Comment by cerenagdas** [comment]
maili gönderdim

**Comment by onuryurtturk** [comment]
teknokent logosu gönderildi https://drive.google.com/file/d/0B4nqLP3OoCKKMnhaWXgzTEtFcXM/edit?usp=sharing
