### ISSUE TITLE
Merve Selçuk

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#46]
Konuşmacılarımızdan Merve Selçuk saat 12:15 - 13:00 arasına eklensin. Fotoğraf onur tarafından gönderilecek. İçerik drive üzerinde mevcut.

Seval Ünver bilgileri ve fotoğrafı :) 16:30 - 17:15 arasına alınsın.

**Comment by cerenagdas** [comment]
https://docs.google.com/document/d/1fbyOmGpDYNobnPbvYVBS2bKptnJlxxZpvZW7mOJTX1U/

**Comment by kemalkanok** [comment]
kişinin resmi bekleniyor

**Comment by cerenagdas** [comment]
https://drive.google.com/file/d/0B-cHrsuZSw6oeGs5TVVFbkZoRnc/edit?usp=sharing
