### ISSUE TITLE
Giriş Sayfasındaki font

### ISSUE THREAD

**Issue by onuryurtturk** [womandevelopersday/womandevelopersday.org#49]
Giriş Sayfasındaki font'u değiştirsek mi? comic sans pek hoş durmuyor sanki?

**Comment by kemalkanok** [comment]
comic olarak karar vermiştik ecem ile birlikte bence hoş ama tasarımcı sensin bir font seçersen haber ver bir de etkinliğe 3 gün kalmadı mı ??? değişiklik yapmak sitede çok da mantıklı gelmiyor
