### ISSUE TITLE
PAU IEEE Logosu

### ISSUE THREAD

**Issue by cerenagdas** [womandevelopersday/womandevelopersday.org#64]
PAU IEEE logosu kaldırılabilir, hiç bir şekilde destek vermediler.

**Comment by kemalkanok** [comment]
Kaldirilabilir mi kaldirilsin mi?

**Comment by cerenagdas** [comment]
Kaldırılsın, emir cümlesi olmasın diye öyle demiştim :)

**Comment by kemalkanok** [comment]
Rica da edebilirdin :)

**Comment by cerenagdas** [comment]
Rica etsem kaldırabilir misin Kemal başkan :)
